import { Grinder } from "./types";

export const grinders: Grinder[] = [
  {
    id: "k_ultra",
    name: "1Zpresso K-Ultra",
    grinder_type: "manual",
    burr_type: "conical",
    fines_bias: "medium",
    scale_type: "clicks",
    ranges: {
      fine_range: "6.4–6.8",
      medium_range: "6.8–7.4",
      coarse_range: "7.6–8.5",
    }
  },
  {
    id: "1zpresso_jx_pro",
    name: "1Zpresso JX-Pro",
    grinder_type: "manual",
    burr_type: "conical",
    fines_bias: "medium",
    scale_type: "rotations",
    ranges: {
      fine_range: "2.0–2.4",
      medium_range: "2.4–3.0",
      coarse_range: "3.0–3.6",
    },
  },
  {
    id: "1zpresso_x_ultra",
    name: "1Zpresso X-Ultra",
    grinder_type: "manual",
    burr_type: "conical",
    fines_bias: "low",
    scale_type: "clicks",
    ranges: {
      fine_range: "1.1–1.6",
      medium_range: "1.6–2.2",
      coarse_range: "2.2–2.8",
    },
  },
  {
    id: "1zpresso_zp6",
    name: "1Zpresso ZP6 Special",
    grinder_type: "manual",
    burr_type: "flat",
    fines_bias: "low",
    scale_type: "clicks",
    ranges: {
      fine_range: "2.5–3.5",
      medium_range: "3.5–4.5",
      coarse_range: "4.5–6.0",
    },
  },
  {
    id: "kingrinder_k_series",
    name: "KINGrinder K-Series (K4 / K6)",
    grinder_type: "manual",
    burr_type: "conical",
    fines_bias: "medium",
    scale_type: "rotations",
    ranges: {
      fine_range: "0.45–0.75",
      medium_range: "0.75–1.1",
      coarse_range: "1.1–1.6",
    },
  },
  {
    id: "kingrinder_p_series",
    name: "KINGrinder P-Series (P0 / P2)",
    grinder_type: "manual",
    burr_type: "conical",
    fines_bias: "high",
    scale_type: "clicks",
    ranges: {
      fine_range: "32–42",
      medium_range: "42–58",
      coarse_range: "58–75",
    },
  },
  {
    id: "timemore_c3",
    name: "Timemore Chestnut C3 / C3S",
    grinder_type: "manual",
    burr_type: "conical",
    fines_bias: "high",
    scale_type: "clicks",
    ranges: {
      fine_range: "11–14",
      medium_range: "14–18",
      coarse_range: "18–24",
    },
  },
  {
    id: "timemore_c5",
    name: "Timemore Chestnut C5",
    grinder_type: "manual",
    burr_type: "conical",
    fines_bias: "medium",
    scale_type: "clicks",
    ranges: {
      fine_range: "6.5–8.0",
      medium_range: "8.0–10.5",
      coarse_range: "10.5–13.0",
    },
  },
  {
    id: "comandante_c40",
    name: "Comandante C40 Mk4",
    grinder_type: "manual",
    burr_type: "conical",
    fines_bias: "low",
    scale_type: "clicks",
    ranges: {
      fine_range: "18–22",
      medium_range: "22–28",
      coarse_range: "28–34",
    },
  },
  {
    id: "kinu_m47",
    name: "Kinu M47",
    grinder_type: "manual",
    burr_type: "conical",
    fines_bias: "low",
    scale_type: "rotations",
    ranges: {
      fine_range: "2.0–2.8",
      medium_range: "2.8–3.8",
      coarse_range: "3.8–5.0",
    },
  },
  {
    id: "hario_skerton",
    name: "Hario Skerton / Ceramic Series",
    grinder_type: "manual",
    burr_type: "conical",
    fines_bias: "high",
    scale_type: "notches",
    ranges: {
      fine_range: "2–3",
      medium_range: "3–5",
      coarse_range: "5–7",
    },
  },
  {
    id: "oxo_conical",
    name: "OXO Conical Burr Grinder",
    grinder_type: "electric",
    burr_type: "conical",
    fines_bias: "medium",
    scale_type: "steps",
    ranges: {
      fine_range: "4–6",
      medium_range: "6–9",
      coarse_range: "9–12",
    },
  },
  {
    id: "niche_zero",
    name: "Niche Zero",
    grinder_type: "electric",
    burr_type: "conical",
    fines_bias: "medium",
    scale_type: "rotations",
    ranges: {
      fine_range: "0.30–0.45",
      medium_range: "0.45–0.65",
      coarse_range: "0.65–0.90",
    },
  },
  {
    id: "baratza_encore",
    name: "Baratza Encore",
    grinder_type: "electric",
    burr_type: "conical",
    fines_bias: "high",
    scale_type: "steps",
    ranges: {
      fine_range: "10–12",
      medium_range: "12–16",
      coarse_range: "16–20",
    },
  },
  {
    id: "baratza_encore_esp",
    name: "Baratza Encore ESP & ESP PRO",
    grinder_type: "electric",
    burr_type: "conical",
    fines_bias: "high",
    scale_type: "steps",
    ranges: {
      fine_range: "18–22",
      medium_range: "23–25",
      coarse_range: "26–30",
    },
  },
  {
    id: "baratza_virtuoso",
    name: "Baratza Virtuoso+",
    grinder_type: "electric",
    burr_type: "conical",
    fines_bias: "medium",
    scale_type: "steps",
    ranges: {
      fine_range: "8–14",
      medium_range: "14–22",
      coarse_range: "22–28",
    },
  },
  {
    id: "breville_bcg820bss",
    name: "Breville Smart Grinder Pro",
    grinder_type: "electric",
    burr_type: "conical",
    fines_bias: "medium",
    scale_type: "digital",
    ranges: {
      fine_range: "21–30",
      medium_range: "31-40",
      coarse_range: "41–60",
    },
  },
  {
    id: "breville_bcg400",
    name: "Breville Dose Control",
    grinder_type: "electric",
    burr_type: "conical",
    fines_bias: "high",
    scale_type: "steps",
    ranges: {
      fine_range: "21–30",
      medium_range: "31-40",
      coarse_range: "41–60",
    },
  },
  {
    id: "breville_bcg600",
    name: "Breville Dose Control Pro",
    grinder_type: "electric",
    burr_type: "conical",
    fines_bias: "medium",
    scale_type: "steps",
    ranges: {
      fine_range: "21–30",
      medium_range: "31-40",
      coarse_range: "41–60",
    },
  },
  {
    id: "fellow_ode_gen2",
    name: "Fellow Ode Gen 2",
    grinder_type: "electric",
    burr_type: "flat",
    fines_bias: "low",
    scale_type: "steps",
    ranges: {
      fine_range: "2.0–3.5",
      medium_range: "3.5–5.5",
      coarse_range: "5.5–7.0",
    },
  },
  {
    id: "fellow_opus",
    name: "Fellow Opus",
    grinder_type: "electric",
    burr_type: "conical",
    fines_bias: "medium",
    scale_type: "steps",
    ranges: {
      fine_range: "3–5",
      medium_range: "5–7",
      coarse_range: "7–9",
    },
  },
  {
    id: "df54",
    name: "DF54",
    grinder_type: "electric",
    burr_type: "flat",
    fines_bias: "medium",
    scale_type: "steps",
    ranges: {
      fine_range: "28–38",
      medium_range: "38–55",
      coarse_range: "55–70",
    },
  },
  {
    id: "df64",
    name: "DF64 (Gen 1 / Gen 2)",
    grinder_type: "electric",
    burr_type: "flat",
    fines_bias: "medium",
    scale_type: "steps",
    ranges: {
      fine_range: "18–25",
      medium_range: "25–40",
      coarse_range: "40–55",
    },
  },
  {
    id: "df64_stock",
    name: "DF64 (Stock Burrs)",
    grinder_type: "electric",
    burr_type: "flat",
    fines_bias: "medium",
    scale_type: "steps",
    ranges: {
      fine_range: "18–20",
      medium_range: "20–24",
      coarse_range: "24–28",
    },
  },
  {
    id: "timemore_064",
    name: "Timemore Sculptor 064",
    grinder_type: "electric",
    burr_type: "flat",
    fines_bias: "low",
    scale_type: "stepless",
    ranges: {
      fine_range: "1.0–3.0",
      medium_range: "3.0–5.5",
      coarse_range: "5.5–7.0",
    },
  },
  {
    id: "timemore_064s",
    name: "Timemore Sculptor 064S",
    grinder_type: "electric",
    burr_type: "flat",
    fines_bias: "low",
    scale_type: "stepless",
    ranges: {
      fine_range: "6.5–7.0",
      medium_range: "7.0–7.8",
      coarse_range: "8.0–9.0",
    },
  },
  {
    id: "timemore_078",
    name: "Timemore Sculptor 078",
    grinder_type: "electric",
    burr_type: "flat",
    fines_bias: "low",
    scale_type: "steps",
    ranges: {
      fine_range: "1.0–3.5",
      medium_range: "3.5–6.0",
      coarse_range: "6.0–8.0",
    },
  },
  {
    id: "timemore_078s",
    name: "Timemore Sculptor 078S",
    grinder_type: "electric",
    burr_type: "flat",
    fines_bias: "low",
    scale_type: "steps",
    ranges: {
      fine_range: "1.0–3.5",
      medium_range: "3.5–6.0",
      coarse_range: "6.0–8.0",
    },
  },
];

export function getGrinderById(id: string): Grinder | undefined {
  return grinders.find((g) => g.id === id);
}
